scrum-and-xp/Models/UpcomingMeeting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace scrum_and_xp.Models
{
    public class UpcomingMeeting
    {
        public int Id { get; set; }       
        public string Description { get; set; }
        public DateTime? Option1 { get; set; }
        public DateTime? Option2 { get; set; }
        public DateTime? Option3 { get; set; }
        public TimeSpan Duration { get; set; }
        public int TotalAnswered { get; set; }
        public ApplicationUser Author { get; set; }

    }
}

scrum-and-xp/ViewModels/MeetingInvitesViewModel.cs
using scrum_and_xp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace scrum_and_xp.ViewModels
{
    public class UpcomingMeetingViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="The meeting needs to have a description")]
        public string Description { get; set; }
        [Required(ErrorMessage ="All the time options need to be filled.")]
        public DateTime? Option1 { get; set; }
        [Required(ErrorMessage ="All the time options need to be filled.")]
        public DateTime? Option2 { get; set; }
        [Required(ErrorMessage = "All the time options need to be filled.")]
        public DateTime? Option3 { get; set; }
        [Required(ErrorMessage ="The meeting needs to have a time duration")]
        public TimeSpan Duration { get; set; }
        public string SelectedResponse { get; set; }
        public ApplicationUser Author { get; set; }
    }

    public class MeetingInvitesViewModel
    {
        public List<UpcomingMeetingViewModel> UpcomingMeetingViewModels { get; set; }
        public List<CreatedInviteViewModel> CreatedInvites { get; set; }
    }   

    public class CreatedInviteViewModel
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public DateTime? Option1 { get; set; }
        public DateTime? Option2 { get; set; }
        public DateTime? Option3 { get; set; }
        public int Option1Votes { get; set; }
        public int Option2Votes { get; set; }
        public int Option3Votes { get; set; }
        public int TotalInvited { get; set; }
        public TimeSpan Duration { get; set; }
        public string SelectedTime { get; set; }
        public ApplicationUser Author { get; set; }
    }

}

scrum-and-xp/Controllers/UpcomingMeetingController.cs
using scrum_and_xp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace scrum_and_xp.Controllers
{
    public class UpcomingMeetingController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult MeetingInvites()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var meetings = db.UsersUpcomingMeetings.Where(m => m.UserId.Id == user.Id).Select(x => x.MeetingId).ToList();
            var model = new List<UpcomingMeetingViewModel>();
            foreach (var item in meetings)
            {
                model.Add(new UpcomingMeetingViewModel { Description = item.Description, Option1 = item.Option1, Option2 = item.Option2, Option3 = item.Option3, Author = item.Author, Duration = item.Duration });
            }
            //var meetings = db.UpcomingMeetings.Where(m => meetingIds.Contains(m.Id)).ToList();
            return View(model);
        }
    }
}

scrum-and-xp/Controllers/UpcomingMeetingsController.cs
using scrum_and_xp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using scrum_and_xp.ViewModels;

namespace scrum_and_xp.Controllers
{
    [Authorize(Roles = "Users,Admin")]
    public class UpcomingMeetingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult MeetingInvites()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var model = new MeetingInvitesViewModel
            {
                UpcomingMeetingViewModels = new List<UpcomingMeetingViewModel>(),
                CreatedInvites = new List<CreatedInviteViewModel>()
            };

            // Meetings the user have been invited to.
            var pendingInvites = db.UsersUpcomingMeetings.Where(m => m.UserId.Id == user.Id && m.Answer == null).Select(x => x.MeetingId).ToList();
            foreach (var item in pendingInvites)
            {
                model.UpcomingMeetingViewModels.Add(new UpcomingMeetingViewModel
                {
                    Id = item.Id,
                    Description = item.Description,
                    Option1 = item.Option1,
                    Option2 = item.Option2,
                    Option3 = item.Option3,
                    Author = item.Author,
                    Duration = item.Duration
                });
            }

            // Meeting invites the user has created.
            var createdUpcomingMeetings = db.UpcomingMeetings.Where(m => m.Author.Id == user.Id).ToList();
            foreach (var item in createdUpcomingMeetings)
            {
                model.CreatedInvites.Add(new CreatedInviteViewModel
                {
                    Id = item.Id,
                    Description = item.Description,
                    Option1 = item.Option1,
                    Option2 = item.Option2,
                    Option3 = item.Option3,
                    Option1Votes = db.UsersUpcomingMeetings.Where(m => m.MeetingId.Id == item.Id && m.Answer == item.Option1 && item.Option1 != null).Count(),
                    Option2Votes = db.UsersUpcomingMeetings.Where(m => m.MeetingId.Id == item.Id && m.Answer == item.Option2 && item.Option2 != null).Count(),
                    Option3Votes = db.UsersUpcomingMeetings.Where(m => m.MeetingId.Id == item.Id && m.Answer == item.Option3 && item.Option3 != null).Count(),
                    TotalInvited = db.UsersUpcomingMeetings.Where(m => m.MeetingId.Id == item.Id).Count(),
                    Author = item.Author,
                    Duration = item.Duration
                });
            }
            //var meetings = db.UpcomingMeetings.Where(m => meetingIds.Contains(m.Id)).ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult MakeSchedulerEvent(int id, DateTime selectedTime)
        {
            var meeting = db.UpcomingMeetings.Include("Author")
                .Where(m => m.Id == id).FirstOrDefault();
            var schedulerEvent = new SchedulerEvent
            {
                Text = meeting.Description,
                StartDate = selectedTime,
                EndDate = selectedTime.AddHours(meeting.Duration.Hours),
                Creator = meeting.Author.Id
            };
            db.SchedulerEvents.Add(schedulerEvent);
            db.UpcomingMeetings.Remove(meeting);
            var result = db.UsersUpcomingMeetings.Where(m => m.MeetingId.Id == meeting.Id);
            foreach (var item in result)
            {
                db.UsersUpcomingMeetings.Remove(item);

            }
            db.SaveChanges();
            return RedirectToAction("MeetingInvites");
        }

        [HttpPost]
        // Reply to meeting invite.
        public ActionResult MeetingInvites(int Id, DateTime SelectedResponse)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var invite = db.UsersUpcomingMeetings.Include("MeetingId").Include("UserId")
                .Where(m => m.MeetingId.Id == Id && m.UserId.Id == user.Id).FirstOrDefault();
            invite.Answer = SelectedResponse;

            var meeting = db.UpcomingMeetings.Find(Id);
            meeting.TotalAnswered += 1;

            var invitedUsers = db.UsersUpcomingMeetings.Include("MeetingId").Include("UserId")
                .Where(m => m.MeetingId.Id == Id && m.Answer != null).Count();
            var totalAnswered = db.UpcomingMeetings.Find(Id).TotalAnswered;

            db.SaveChanges();
            return RedirectToAction("MeetingInvites");
        }

        public ActionResult Create()
        {
            var model = new CreateUpcomingMeetingViewModel();
            model.AllUsers = db.Users.ToList();
            //ViewBag.AllUsers = new SelectList(db.Users.ToList(), "Id", "Email");
            ViewBag.InvitedUsers = new List<SelectListItem>();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(CreateUpcomingMeetingViewModel model, List<string> invitedUsers)
        {
            // Check if the time options are the same time.
            var options = new List<DateTime?> { model.Option1, model.Option2, model.Option3 };
            for (int i = 0; i < options.Count; i++)
            {
                if ((i + 1) != options.Count)
                {
                    if (options[i] == options[i + 1] && options[i] != null && options[i + 1] != null)
                    {
                        if (ModelState.ContainsKey("Option3"))
                        {
                            ModelState["Option3"].Errors.Clear();
                            ModelState.AddModelError("Option3", "All option times need to be different.");
                        }
                    }
                }
            }

            if (ModelState.IsValid)
            {
                var newMeeting = new UpcomingMeeting()
                {
                    Author = db.Users.Find(User.Identity.GetUserId()),
                    Description = model.Description,
                    Duration = model.Duration,
                    Option1 = model.Option1,
                    Option2 = model.Option2,
                    Option3 = model.Option3
                };
                db.UpcomingMeetings.Add(newMeeting);
                foreach (var id in invitedUsers)
                {
                    var user = db.Users.Find(id);
                    var attendee = new UsersUpcomingMeetings()
                    {
                        UserId = user,
                        MeetingId = newMeeting
                    };
                    db.UsersUpcomingMeetings.Add(attendee);
                }

                db.SaveChanges();
                return RedirectToAction("MeetingInvites");
            }
            ViewBag.InvitedUsers = new List<SelectListItem>();
            return View(model);
        }
    }
}

scrum-and-xp/Views/UpcomingMeetings/Create.cshtml
@model scrum_and_xp.ViewModels.CreateUpcomingMeetingViewModel

@{
    ViewBag.Title = "CreateUpcomingMeeting";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "UpcomingMeetings"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Upcoming Meeting Invite</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option1, new { htmlAttributes = new { @class = "form-control", placeholder = "yyyy-mm-dd hh:mm" } })
                @Html.ValidationMessageFor(model => model.Option1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option2, new { htmlAttributes = new { @class = "form-control", placeholder = "yyyy-mm-dd hh:mm" } })
                @Html.ValidationMessageFor(model => model.Option2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Option3, new { htmlAttributes = new { @class = "form-control", placeholder = "yyyy-mm-dd hh:mm" } })
                @Html.ValidationMessageFor(model => model.Option3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control", placeholder = "hh:mm" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        @*@foreach (var item in Model.AllUsers)
            {
                <a id="@item.Id" class="invite-btn btn-primary btn-sm">@item.FirstName @item.LastName - Invite</a>
            }*@

        @Html.ListBox("AllUsers", new SelectList(Model.AllUsers, "Id", "Email"), new { multiple = "multiple", style = "min-width: 200px; margin-left: 200px;"})
        <br />
        <input id="ShiftRight" type="button" value="Invite selected user(s)" class="btn btn-default btn-sm" style="margin-left: 200px;" />
        <br /><br />
        @Html.ListBox("InvitedUsers", null, new { multiple = "multiple", style = "min-width: 200px; margin-left: 200px;" })
        <br />
        <input id="ShiftLeft" type="button" value="Uninvite selected user(s)" class="btn btn-default btn-sm" style="margin-left: 200px;" />
        <br />

        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "MeetingInvites")
</div>

@section Scripts {
    <script>
        function test() {
            window.location.href = "https://www.google.se";
        }
        var invitedUsers = [];
        $('a.invite-btn').click(function () {
            var id = $(this).attr('id');
            invitedUsers.push(id);
        });

        $(function () {
            $("#ShiftRight,#ShiftLeft").click(function (event) {
                var ID = $(event.target).attr("ID");
                var ChooseFrom = ID == "ShiftRight" ? "#AllUsers" : "#InvitedUsers";
                var moveTo = ID == "ShiftRight" ? "#InvitedUsers" : "#AllUsers";
                var SelectData = $(ChooseFrom + " :selected").toArray();
                $(moveTo).append(SelectData);
                SelectData.remove;
            });
        });


    </script>
}

scrum-and-xp/Views/UpcomingMeetings/MeetingInvites.cshtml
@model scrum_and_xp.ViewModels.MeetingInvitesViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Upcoming Meetings</h2>

<p>
    @Html.ActionLink("Create New Meeting Invite", "Create", "UpcomingMeetings")
</p>

<h4>Created Invites</h4>
<table class="table">
    <tr>
        <th>
            Description
        </th>
        <th>
            Duration <br />
            (hh:mm:ss)
        </th>
        <th>
            Option 1 Votes
        </th>
        <th>
            Option 2 Votes
        </th>
        <th>
            Option 3 Votes
        </th>
        <th>
            Replies / <br />
            Total Invited
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.CreatedInvites)
    {
        using (Html.BeginForm("MakeSchedulerEvent", "UpcomingMeetings"))
        {
            @Html.AntiForgeryToken()
            <tr>
                <td>
                    @item.Description
                </td>
                <td>
                    @item.Duration
                </td>
                <td>
                    @if (item.Option1 != null)
                    {
                        @item.Option1
                        <br />
                        <b>@item.Option1Votes</b>
                        @Html.RadioButton("SelectedTime", item.Option1)
                    }
                </td>
                <td>
                    @if (item.Option2 != null)
                    {

                        @item.Option2
                        <br />
                        <b>@item.Option2Votes</b>
                        @Html.RadioButton("SelectedTime", item.Option2)
                    }
                </td>
                <td>
                    @if (item.Option3 != null)
                    {
                        @item.Option3
                        <br />
                        <b>@item.Option3Votes</b>
                        @Html.RadioButton("SelectedTime", item.Option3)
                    }
                </td>
                <td>
                    @{ var replies = item.Option1Votes + item.Option2Votes + item.Option3Votes;
                        <b>
                            @replies / @item.TotalInvited
                        </b>
                    }
                </td>
                <td>
                    @Html.Hidden("id", item.Id)
                    <input type="submit" value="Create Meeting" />
                </td>
            </tr>
        }
    }

</table>

<h4>Pending Invites</h4>
<table class="table">
    <tr>
        <th>
            Invited by
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpcomingMeetingViewModels.First().Description)
        </th>
        <th>
            Duration <br />
            (hh:mm:ss)
        </th>
        <th>
            Option 1
        </th>
        <th>
            Option 2
        </th>
        <th>
            Option 3
        </th>

        <th></th>
        <th></th>
    </tr>

    @foreach (var item in Model.UpcomingMeetingViewModels)
    {
        using (Html.BeginForm())
        {

            @Html.AntiForgeryToken()
            <tr>
                <td>
                    @item.Author.FirstName @item.Author.LastName
                </td>
                <td>
                    @Html.DisplayFor(m => item.Description)
                </td>
                <td>
                    @item.Duration 
                </td>
                <td>
                    @if (item.Option1 != null)
                    {
                        @item.Option1@: - <br />
                        var endDate = new DateTime(Convert.ToDateTime(item.Option1).Ticks).AddHours(item.Duration.Hours);
                        @endDate
                        @Html.RadioButton("SelectedResponse", item.Option1, new { style = "margin-left: 5px;"})
                    }
                </td>
                <td>
                    @if (item.Option2 != null)
                    {
                        @item.Option2@:- <br />
                        var endDate2 = new DateTime(Convert.ToDateTime(item.Option2).Ticks).AddHours(item.Duration.Hours);
                        @endDate2
                        @Html.RadioButton("SelectedResponse", item.Option2, new { style = "margin-left: 5px;"})
                    }
                </td>
                <td>
                    @if (item.Option3 != null)
                    {
                        @item.Option3@: - <br />
                        var endDate3 = new DateTime(Convert.ToDateTime(item.Option3).Ticks).AddHours(item.Duration.Hours);
                        @endDate3
                        @Html.RadioButton("SelectedResponse", item.Option3, new { style = "margin-left: 5px;"})
                    }
                </td>
                <td>
                    @Html.Hidden("Id", item.Id)
                    @Html.Hidden("Author", item.Author)
                    @Html.Hidden("Duration", item.Duration)
                </td>
                <td><input type="submit" value="Pick time" /> </td>
            </tr>
        }
    }

</table>
@section Scripts{
    <script>

    </script>
}